parserOptions:
  ecmaFeatures:
    modules: false
env:
  es6: true
  browser: true
rules:
  strict:
    - error
    - global
  complexity:
    - error
    - max: 15
  max-lines-per-function:
    - error
    - max: 50
  max-statements:
    - error
    - max: 50
extends:
  - eslint:recommended
  - plugin:no-unsanitized/DOM
  - prettier
