name: autoupdate workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ci-tests-${{github.ref}}-autoupdate
  cancel-in-progress: true

jobs:
  autoupdate_job:
    name: autoupdate job
    runs-on: ubuntu-latest
    steps:
      - name: attempt autoupdate with PAT
        # if we don't use a PAT, then the pull-request event will fire after auto-update.
        # if no pull-request event fires, then our testing cannot run again, and so auto-merge would be impossible
        id: autoupdate_pat
        continue-on-error: true
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{secrets.PAT}}"
          PR_FILTER: "protected"

      - name: fallback to autoupdate with GITHUB_TOKEN
        if: steps.autoupdate_pat.outcome != 'success'
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          PR_FILTER: "protected"
