name: autoupdate workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ci-tests-${{github.ref}}-autoupdate
  cancel-in-progress: true

jobs:
  autoupdate_job:
    name: autoupdate job
    runs-on: ubuntu-latest
    steps:
      - name: autoupdate with GITHUB_TOKEN
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          PR_FILTER: "protected"
