name: release workflow

on:
  release:
    types: [published]

concurrency:
  group: ci-tests-${{github.ref}}-release
  cancel-in-progress: true

jobs:
  release_job:
    runs-on: ubuntu-latest
    name: release job
    steps:
      - name: print context info
        run: |
          echo github: '${{github}}'
