name: release workflow

on:
  release:
    types: [published]

concurrency:
  group: ci-tests-${{github.ref}}-release

jobs:
  test_pypi_deploy_job:
    runs-on: ubuntu-latest
    name: deploy to test pypi job
    env:
      REPO_URL: https://test.pypi.org/legacy/
      PYPI_USER: grintor
    environment:
      name: test.pypi.org
      url: https://test.pypi.org/project/cylinder/
    steps:
      - run: .ci-tools/release_publisher.py ${{github.ref_name}}

  prod_pypi_deploy_job:
    runs-on: ubuntu-latest
    name: deploy to production pypi job
    needs: test_pypi_deploy_job
    env:
      REPO_URL: https://upload.pypi.org/legacy/
      PYPI_USER: grintor
    environment:
      name: pypi.org
      url: https://pypi.org/project/cylinder/
    steps:
      - run: .ci-tools/release_publisher.py ${{github.ref_name}}
